Abundance_estimation/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('processing.views',
    url(r'^$', 'home', name='home'),
    url(r'^bowtie/$', 'bowtie_form'),
    url(r'^bwa/$', 'bwa_form'),
    url(r'^diffexp/$', 'diffexp_form'),
    url(r'^register/$', 'register_user'),
    url(r'^login/$', 'log_in'),
    url(r'^login/auth/$', 'auth_view'),
    url(r'^logout/$', 'log_out'),
    url(r'^files/$', 'show_files'),
    url(r'^process/$', 'show_processes'),
    url(r'^files/upload/$', 'show_fileupload', name='file_upload'),
    url(r'^files/submit/$', 'filesubmit'),
    url(r'^files/success/$', 'upload_success', name='upload_success'),
    url(r'^files/delete/(\d+)/$', 'delete_file'),
    url(r'^files/edit/(\d+)/$', 'show_edit_file', name='show_edit_file'),
    url(r'^files/(?P<id_file>\d+)/$', 'download_file', name="download_file"),
    url(r'^process/show/(?P<process_id>\d+)/$', 'show_specific_process', name="show_specific_process"),
    url(r'^process/show/$', 'show_process', name='show_process'),
    url(r'^editfile/$', 'editfile'),
    url(r'^mapping/$', 'mapping'),
    url(r'^Abundance_estimation/$', 'Abundance_estimation'),
    # Examples:
    # url(r'^$', 'Abundance_estimation.views.home', name='home'),
    # url(r'^Abundance_estimation/', include('Abundance_estimation.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

ExpDiff/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('processing.views',
    url(r'^$', 'home', name='home'),
    url(r'^bowtie/$', 'bowtie_form'),
    url(r'^bwa/$', 'bwa_form'),
    url(r'^diffexp/$', 'diffexp_form'),
    url(r'^register/$', 'register_user'),
    url(r'^login/$', 'log_in'),
    url(r'^login/auth/$', 'auth_view'),
    url(r'^logout/$', 'log_out'),
    url(r'^files/$', 'show_files'),
    url(r'^process/$', 'show_processes'),
    url(r'^files/upload/$', 'show_fileupload', name='file_upload'),
    url(r'^files/submit/$', 'filesubmit'),
    url(r'^files/success/$', 'upload_success', name='upload_success'),
    url(r'^files/delete/(\d+)/$', 'delete_file'),
    url(r'^files/edit/(\d+)/$', 'show_edit_file', name='show_edit_file'),
    url(r'^files/(?P<id_file>\d+)/$', 'download_file', name="download_file"),
    url(r'^process/show/(?P<process_id>\d+)/$', 'show_specific_process', name="show_specific_process"),
    url(r'^process/show/$', 'show_process', name='show_process'),
    url(r'^editfile/$', 'editfile'),
    url(r'^mapping/$', 'mapping'),
    # Examples:
    # url(r'^$', 'ExpDiff.views.home', name='home'),
    # url(r'^ExpDiff/', include('ExpDiff.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

processing/models.py
# -*- coding: utf-8 -*-
from django.db import models
import subprocess
import threading
from django.conf import settings
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.models import User
from time import sleep
from django.core.files import File as Django_File
from django.conf import settings
from random import randint

# Opciones estáticas
POSIBLES_ESTADOS_PROCESOS = (
    (0, "Terminado exitosamente"),
    (1, "Terminado con errores"),
    (2, "Iniciado"),
    (3, "En espera")
)
MAPEADORES = (
    (0, "BWA"),
    (1, "Bowtie"),
)
TIPOS_MAPEO = (
    (0, "Single end"),
    (1, "Paired end")
)


class Profile(models.Model):
    user = models.OneToOneField(User)
    email = models.EmailField()
    firstName = models.CharField(max_length=30)
    lastName = models.CharField(max_length=30)

    class Meta:
        verbose_name_plural = 'Perfiles'

    def __unicode__(self):
        return unicode(self.email)


class File(models.Model):
    fileUpload = models.FileField()
    description = models.TextField(default="")
    profile = models.ForeignKey(Profile)
    ext = models.CharField(max_length=7)

    class Meta:
        verbose_name_plural = 'Archivos'

    def __unicode__(self):
        return u"ARCHIVO \n Location: %s \n Description: %s " % (self.fileUpload.path, self.description)


class Proceso(models.Model):

    estado = models.IntegerField(choices=POSIBLES_ESTADOS_PROCESOS, default=3)
    std_err = models.TextField(default="")
    std_out = models.TextField(default="")
    comando = models.CharField(max_length=2000, default="echo Hola mundo")
    profile = models.ForeignKey(Profile)

    class Meta:
        verbose_name_plural = 'Procesos'

    def get_estado(self):
        return POSIBLES_ESTADOS_PROCESOS[self.estado][1]

    def run_process(self):
        self.estado = 2
        self.save()
        try:
            p = subprocess.Popen(str(self.comando), stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
            self.std_out, self.std_err = p.communicate()
            self.estado = p.returncode
        except:
            try:
                self.std_out, self.std_err = p.communicate()
                self.estado = 0
                self.save()
            except:
                self.estado = 0
                self.save()
        #  self.std_out = self.std_out.replace("\n", "<br>")
        #  self.std_err = self.std_err.replace("\n", "<br>")
        self.save()

    def run(self):
        t = threading.Thread(target=self.run_process)
        t.setDaemon(True)
        t.start()

    def __unicode__(self):
        return u"ID: %s Estado: %s \n Comando: %s \n STDOUT: \n %s \n STDERR: %s\n " % (str(self.id), str(self.estado), str(self.comando), str(self.std_out), str(self.std_err))


class Mapeo(models.Model):

    """"
    Ejemplo de mapeo
    type=1 -> Single end
    type=2 -> Paired end
    m = Mapeo(name="Exp", mapeador=0, tipo=1, profile=p)
    m.save()
    m.run_bowtie(reference="/home/null3d/Softs_ud/Abundace_Estimation-ud/files/ecoli.fa", reads_1=["/home/null3d/Softs_ud/Abundace_Estimation-ud/files/es_1_1_10k.fq"], reads_2=["/home/null3d/Softs_ud/Abundace_Estimation-ud/files/es_1_1_10k.fq"])
    """
    name = models.TextField(default="Experimento")
    procesos = models.ManyToManyField(Proceso)
    mapeador = models.IntegerField(choices=MAPEADORES, default=1)
    tipo = models.IntegerField(default=1, choices=TIPOS_MAPEO)
    profile = models.ForeignKey(Profile)
    out_file = models.ForeignKey(File, null=True)

    def run_bowtie(self, reference="", reads_1="", reads_2="", reads_se="", tipo=1):
        self.name = "Experimento %s" % self.id
        self.save()
        reference_file = reference  # Full path
        reference_path = reference_file[::-1].split("/", 1)[1][::-1]
        reference_index = reference_path + "/" + reference_file.split("/")[-1].replace(" ", "_").replace(".fasta", "").replace(".fa", "")
        comando = "bowtie-build %s %s" % (reference_file, reference_index)
        p1 = Proceso(comando=str(comando), profile=self.profile)
        p1.save()
        self.procesos.add(p1)
        # To get files with path trin.fileUpload.path
        # Genero indice y espero hasta que este listo
        t1 = threading.Thread(target=p1.run_process)
        t1.setDaemon(True)
        t1.start()
        while t1.isAlive():
            sleep(1)
        file_name = "/tmp/%s.bam" % self.name.replace(" ", "_")
        tmp_sam = "/tmp/%s" % ("tmp_%s.sam" % randint(1, 1000000))
        if self.tipo == 1:
            mates1 = ','.join(reads_1)
            mates2 = ','.join(reads_2)
            # out_bam = "%s.bam" % self.name.replace(" ", "_")samtools view -Sb - > hits.bam
            comando = "bowtie -a -S -p %s  %s -1 %s -2 %s %s  " % (settings.CORES, reference_index, mates1, mates2, tmp_sam)
        elif self.tipo == 0:
            mates = ",".join(reads_se)
            comando = "bowtie -a -S -p %s  %s -s %s  %s | samtools view -bSx - > %s " % (settings.CORES, reference_index, mates, tmp_sam)
        p2 = Proceso(comando=str(comando), profile=self.profile)
        p2.save()
        print p2
        self.procesos.add(p2)
        t2 = threading.Thread(target=p2.run_process)
        t2.setDaemon(True)
        t2.start()
        while t2.isAlive():
            sleep(1)
        comando = "samtools view -bS  %s -o %s" % (tmp_sam, file_name)
        p3 = Proceso(comando=str(comando), profile=self.profile)
        p3.save()
        self.procesos.add(p3)
        t3 = threading.Thread(target=p3.run_process)
        t3.setDaemon(True)
        t3.start()
        while t3.isAlive():
            sleep(1)
        self.save()
        out_file = File(fileUpload=Django_File(open(file_name)), description="Salida " + self.name, profile=self.profile, ext="bam")
        out_file.save()
        self.out_file = out_file

    def run(self, reference, reads_1="", reads_2="", reads_se="", tipo=1):
        t = threading.Thread(target=self.run_bowtie, kwargs=dict(reference=reference, reads_1=reads_1, reads_2=reads_2, reads_se=reads_se, tipo=tipo))
        t.setDaemon(True)
        t.start()

    class Meta:
        verbose_name_plural = "Procesos de mapeo"

    def __unicode__(self):
        return "MAPEO \n %s" % self.name


class Abundace_Estimation(models.Model):
    name = models.TextField(default="Abundace_Estimation Results")
    procesos = models.ManyToManyField(Proceso)
    out_results = models.ForeignKey(File, null=True, related_name="file_results_Abundace_Estimation")
    out_params = models.ForeignKey(File, null=True, related_name="file_rparams_Abundace_Estimation")
    profile = models.ForeignKey(Profile)

    def run_express(self, reference="", bam_file=""):
        self.name = "Abundace_Estimation Results. Exp: %s " % self.id
        self.save()
        out_dir = "/tmp/xprs_out%s" % str(randint(1, 65000))
        comando = "express -o %s %s %s" % (str(out_dir), reference, bam_file)
        p = Proceso(comando=str(comando), profile=self.profile)
        p.save()
        self.procesos.add(p)
        t1 = threading.Thread(target=p.run_process)
        t1.setDaemon(True)
        t1.start()
        while t1.isAlive():
            sleep(1)
        f1 = File(fileUpload=Django_File(open(out_dir + "/" + "results.xprs")), description="Salida " + self.name, profile=self.profile, ext="xprs")
        f1.save()
        self.out_results = f1
        f2 = File(fileUpload=Django_File(open(out_dir + "/" + "params.xprs")), description="Salida " + self.name, profile=self.profile, ext="xprs")
        f2.save()
        self.out_params = f2
        self.save()

    def run(self, reference="", bam_file=""):
        #  self.name = "Experimento %s" % self.id
        #  self.save()
        t = threading.Thread(target=self.run_express, kwargs=dict(reference=reference, bam_file=bam_file))  # Replace for bwa when ready
        t.setDaemon(True)
        t.run()

    def __unicode__(self):
        print name

    class Meta:
        verbose_name_plural = "Procesos de  estimar abundancia"  

processing/forms.py
from django import forms
from django.db import models


class UploadFileForm(forms.Form): 
    title = forms.CharField(max_length=50) 
    fileUploaded = forms.FileField() 
    description = models.TextField(max_length=200)

Abundance_estimation/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">    
    
    <title>{% block title %}AbEst{% endblock %}</title>
        <!-- Latest compiled and minified JavaScript and JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-sm-12">
        <nav class="navbar navbar-default" role="navigation">
          <div class="container-fluid">
              
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <a class="navbar-brand" href="/">AbEst</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                {% if user.is_authenticated %}
                
                    
                {% endif %}
                {% if not user.is_authenticated %}
                    <li><a href="/register/">Registrarse</a></li>
                    <li><a href="/login/">Acceder</a></li>
                {% else %}
                    <li><a href="/logout/">Salir</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li><a href="/files/">Mis Archivos</a></li>
                    <li><a href="/process/show/">Lista de Procesos</a></li>
                {% endif %}

              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        </div>
    </div>
            {% block content %}{% endblock %}
</div>
</body>
</html>

Abundance_estimation/templates/diffexp_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/diffexp/">Estimación de abundancia</a></li>
            <li><a href="/bowtie/">Bowtie</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            Estimación de abundancia
        </h1><br><br>
        <form action="/Abundance_estimation/" method="post">
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="id_reference">Archivo de referencia:</label>
                    <select class="form-control" id="id_reference" name="reference"  required>
                        <option value="">seleccione un archivo</option>
                        {% for f in fastaList %}
                            <option value='{{f.id}}'>{{f.fileUpload.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="id_transcriptome">Archivo SAM:</label>
                    <select class="form-control" id="id_transcriptome" name="transcriptome">
                        <option value="">seleccione un archivo</option>
                        {% for b in bamList %}
                            <option value='{{b.id}}'>{{b.fileUpload.name}}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <button type="submit" class="btn btn-default">Send</button>
            </form>
    </div>
</div>

{% endblock %}

Abundance_estimation/templates/error.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">

    </div>
    <div class="col-sm-6">
        <div class="alert alert-danger">
            Error:<br><br>
            {{error}}
        </div>
    </div>
    <div class="col-sm-3">

    </div>
</div>

{% endblock %}

Abundance_estimation/templates/files.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/files/upload/">Subir Archivo</a></li>
            <li><a href="/process/show/">Lista de procesos</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            Lista de archivos
        </h1>
        <div class="list-group">
            {% for f in file_list %}
                <div href="#" class="list-group-item glyphicon glyphicon-file">
                    <span class="" title="Description: {{f.description}}">
                        {{f.fileUpload.name|truncatechars:50}}
                    </span>
                    <span class="pull-right">
                        <span class="label label-success glyphicon glyphicon-edit" style="display: table-cell;">
                            <a style="color:white" href="/files/edit/{{f.id}}">Editar
                            </a>
                        </span>
                        <span class="label label-danger glyphicon glyphicon-remove" style="display: table-cell;">
                            <a style="color:white" href="/files/delete/{{f.id}}">Borrar 
                            </a>
                        </span>
                        <span class="label label-success glyphicon glyphicon-download" style="display: table-cell;">
                            <a style="color:white" href="/files/{{f.id}}/">Descargar 
                            </a>
                        </span>
                        
                    </span>
                    
                </div> 
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

Abundance_estimation/templates/fileupload.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/files/">Mis archivos</a></li>
            <li><a href="/process/show/">Lista de procesos</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        
        <h1>
            Subir Archivo
        </h1>
        <form action="/files/submit/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_description"><h4>Descripción del archivo:</h4></label>
                    <input class="form-control" id="id_description" name="description" type="text">
                </div>
                <div class="form-group">
                    <label for="id_fileUploaded"><h4>Archivo:</h4></label>
                    <input class="form-control" id="id_fileUploaded" name="file" type="file">
                </div>
                <button type="submit" class="btn btn-default">Subir</button>
            </form>

    </div>
</div>

{% endblock %}

Abundance_estimation/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/diffexp/">Estimación de abundancia</a></li>
            <li><a href="/bowtie/">Bowtie</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            AbEst
        </h1><br>
        <p>
            <div class="row">
                <div class="col-md-9" style='text-align:justify;'>
                    AbEst facilita el proceso de realizar estimación de abundancia en un análisis RNA-Seq principalmente a los investigadores no relacionados con el área de informática brindando una interfaz amigable orientada a la web para el uso  de herramientas que solo están disponibles para uso a través de línea de comandos.
                </div>
            </div>
        </p>
        <br>
    </div>
</div>

{% endblock %}

Abundance_estimation/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
        <form role="form" action="/login/auth/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="email">Correo electronico</label>
                <input type="email" class="form-control" name="email" id="email" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label for="password">Contraseña</label>
                <input type="password" class="form-control" name="password" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-default">Acceder</button>
        </form>
        <div class="row">
            <p class="text-muted">¿No posee una cuenta?: <a href="/register/">Registrarse</a></p>
        </div>
    </div>
    <div class="col-sm-4"></div>
</div>
{% endblock %}

Abundance_estimation/templates/logout.html
{% extends "base.html" %}
{% block content %}
    la sesion fue cerrada: <a href="/">home</a>
{% endblock %}

Abundance_estimation/templates/processes.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/files/upload/">Upload file</a></li>
            <li><a href="/files/">Mis Archivos</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            Lista de procesos
        </h1>
        A continuacion se listan los procesos que ha corrido en el sistema
        <table class="table">
        <thead>
            <tr>
                <th>Comando</th>
                <th>Estado</th>
                <th>Ver </th>
            </tr>
        </thead>
        <tbody>
            {% for p in process_list %}
            <tr>
                <td>{{p.comando|slice:":65"}}</td>
                <td>{{p.get_estado}}</td>
                <td> <a href="/process/show/{{p.id}}/">Ver</a>

            </tr>
            {% endfor %}
        </tbody>

    </div>
</div>

{% endblock %}

Abundance_estimation/templates/register.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <h2>Registro</h2><br>
            <form action="/register/" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_email">Correo electronico:</label>
                    <input class="form-control" id="id_email" maxlength="75" name="email" type="email">
                </div>
                <div class="form-group">
                    <label for="id_firstName">Nombres:</label>
                    <input class="form-control" id="id_firstName" maxlength="30" name="firstName" type="text">
                </div>
                <div class="form-group">
                    <label for="id_lastName">Apellidos:</label>
                    <input class="form-control" id="id_lastName" maxlength="30" name="lastName" type="text">
                </div>
                <div class="form-group">
                    <label for="id_password1">Contraseña:</label>
                    <input class="form-control" id="id_password1" name="password1" type="password">
                </div>
                <div class="form-group">
                    <label for="id_password2">Repetir contraseña:</label>
                    <input class="form-control" id="id_password2" name="password2" type="password">
                </div>
                <button type="submit" class="btn btn-default">Registrarse</button>
            </form>
        </div>
        <div class="col-sm-3"> </div>
    </div>
    {% endblock %}

Abundance_estimation/templates/registration_success.html
{% extends "base.html" %}
{% block content %}
el registro fue todo un exito :D
{% endblock %}

Abundance_estimation/templates/show_process_info.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/files/upload/">Subir archivo</a></li>
            <li><a href="/files/">Mis archivos</a></li>
            <li><a href="/process/show/">Lista de procesos</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h3>
            Comando:
        </h3>
           <pre> {{p.comando}} </pre>
        <h3> 
            Estado:
        </h3>
            <pre> {{p.get_estado}}</pre>
        <h3> 
            Standard Error
        </h3>
            <pre> {{p.std_err}} </pre>
        <h3> 
            Standard Output
        </h3>
           <pre>  {{p.std_out}}</pre>
    </div>
</div>

{% endblock %}

Abundance_estimation/templates/show_processes.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <nav style="border-radius: 5px; border: solid rgb(161, 161, 161) 2px;">
          <ul class="nav nav-pills nav-stacked span2">
            <li><a href="/files/upload/">Subir archivo</a></li>
            <li><a href="/files/">Mis archivos</a></li>
          </ul>
        </nav>
    </div>
    <div class="col-sm-9" style="border-left: solid rgb(80, 121, 150) 1px;">
        <h1>
            Files list
        </h1>
        <div class="list-group">
            {% for f in file_list %}
                <div href="#" class="list-group-item glyphicon glyphicon-file">
                    <span class="" title="Description: {{f.description}}">
                        {{f.fileUpload.name}}
                    </span>
                    <span class="pull-right">
                        <span class="label label-success glyphicon glyphicon-edit">
                            <a style="color:white" href="/files/edit/{{f.id}}">
                            Edit
                            </a>
                        </span>
                        <span class="label label-danger glyphicon glyphicon-remove">
                            <a style="color:white" href="/files/delete/{{f.id}}">
                            Delete 
                            </a>
                        </span>
                        
                    </span>
                    
                </div> 
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

Abundance_estimation/templates/upload_success.html
{% extends "base.html" %}
{% block content %}
el archivo se subio con exito :D
<br>
<a href="/files/">Go to my files</a>
{% endblock %}